services:
  api:
    build: ./docker/api
    ports:
      - 8080:80
    restart: always
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: database
    # You definitely shouldn't just have this here
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
  grafana:
    build: ./docker/grafana
    ports:
      - 3000:3000
    restart: always
    # environment: 
    #   GF_INSTALL_PLUGINS=
    volumes:
      - gfdata:/var/lib/grafana
  worker:
    build: ./docker/worker
    depends_on:
      - db

volumes:
  pgdata:
  
  gfdata:
    external: true



