services:
  api:
    build: ./docker/api
    ports:
      - 8080:80
    restart: always
    depends_on:
      - db
  db:
    build: ./docker/db
    restart: always
    # You definitely shouldn't just have this here
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
  grafana:
    build: ./docker/grafana
    ports:
      - 3000:3000
    restart: always
    # environment: 
    #   GF_INSTALL_PLUGINS=
    depends_on:
      - api
  worker:
    build: ./docker/worker
    depends_on:
      - db
    restart: any

volumes:
  pgdata:





